[package]
name = "k8s-pki"
version = "0.0.0-development"
edition = "2021"

[dependencies]
clap = { version = "3.2.22", features = ["derive", "env"] }
env_logger = "0.9.1"
k8s-openapi = { version = "0.15.0", features = ["v1_22"] }
kube = "0.74.0"
log = "0.4.17"
openssl = "0.10.42"
openssl-sys = "0.9.75"
prost = "0.10.4"
prost-types = "0.10.1"
time = "0.3.14"
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread", "fs", "signal"] }
tonic = { version = "0.7.2", features = ["tls", "tls-roots", "tls-roots-common"] }
tonic-types = "0.5.0"
tonic-web = "0.3.0"

[dev-dependencies]
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.7.2"
