name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/wirepact/k8s-pki:latest
            ghcr.io/wirepact/k8s-pki:${{ github.sha }}
            ghcr.io/wirepact/k8s-pki:${{ env.BUILD_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
